### ISSUE TITLE
Change the color scheme to be purple

### ISSUE THREAD

**Issue by nedjulius** [BUGS-NYU/nyu-cs-wiki#12]
I think that it would be great if we changed the color scheme to align with our bugs theme and the general NYU theme (purple). What do you think?

This feature would require to change the `custom.css` file (https://github.com/BUGS-NYU/nyu-cs-wiki/blob/main/src/css/custom.css).

**Comment by nedjulius** [comment]
We can refer to the tailwind color schemes (https://tailwindcss.com/docs/text-color) since we are primarily using their default colors.

**Comment by Yasir761** [comment]
> I think that it would be great if we changed the color scheme to align with our bugs theme and the general NYU theme (purple). What do you think?
> 
> This feature would require to change the `custom.css` file (https://github.com/BUGS-NYU/nyu-cs-wiki/blob/main/src/css/custom.css).

 Are you saying to change the banner color scheme to purple from green?

**Comment by nedjulius** [comment]
> > I think that it would be great if we changed the color scheme to align with our bugs theme and the general NYU theme (purple). What do you think?
> > This feature would require to change the `custom.css` file (https://github.com/BUGS-NYU/nyu-cs-wiki/blob/main/src/css/custom.css).
> 
> Are you saying to change the banner color scheme to purple from green?

No, I am saying to change the general color scheme of the wiki. Changing the primary color should be sufficient.

![Screen Shot 2023-03-29 at 10 57 05](https://user-images.githubusercontent.com/45975811/228580199-aa00f47e-181f-4e17-a440-12fe85128a87.png)

**Comment by calvinatian** [comment]
* #13
