### ISSUE TITLE
Add resources for international students

### ISSUE THREAD

**Issue by nedjulius** [BUGS-NYU/nyu-cs-wiki#15]
We have a lot of international CS students. It would be great to add a condensed version about internships and Visa eligibility for international students (which also links to the good resources provided by NYU OGS).

**Comment by aminoa** [comment]
A couple additional topics besides the above:

- Improving English comprehension and speaking (from [this link](https://www.nyu.edu/students/student-information-and-resources/career-development-and-jobs/global-career-resources/international-student-services.html)):
- International Student Support Center (more info [here](https://www.sps.nyu.edu/homepage/student-experience/International-Students.html))
