### ISSUE TITLE
Separate Section for Recruiting

### ISSUE THREAD

**Issue by aminoa** [BUGS-NYU/nyu-cs-wiki#18]
There is a lot of information that could be put here (preparing for interviews, leetcoding, NYU resources, when to apply, different events for companies (ex. JP Code for Good), ex) such that placing this information in a separate section would make it cleaner to use the website.

**Comment by sachiniyer** [comment]
I would argue a separate section for all opportunities.

- Fellowships
- Research
- Internships

It would also be good to talk about how to achieve each of these and the positives/negatives of each one.

**Comment by sachiniyer** [comment]
I have addressed this issue in #26
