### ISSUE TITLE
NYU CS Student Discounts Section?

### ISSUE THREAD

**Issue by kazisean** [BUGS-NYU/nyu-cs-wiki#24]
Maybe a section listing up-to-date NYU student discounts? This could also include general cs student discounts to products such as digital ocean, notion, GitHub pro, etc. Just a hub for all the information in one place instead of jumping through hoops on Google. Light introduction on tools & Services offered at the NYU MakerSpace etc.

**Comment by sachiniyer** [comment]
I think you could probably make a PR on this in the [Social](https://nyucswiki.com/docs/Social) section? But not super sure where it should go.

Some that you named:
- Digital Ocean
- Notion
- Github pro
- Makerspace

Some that I would add:
- NYU HPC
- Some stuff from [This List](https://github.com/kamath/student-free-stuff)
- Handshake
- NYU Computer Labs
