### ISSUE TITLE
Rename social tab

### ISSUE THREAD

**Issue by calvinatian** [BUGS-NYU/nyu-cs-wiki#46]
I think the "Social" tab should be renamed. I don't think "Social" fits in with what the category describes. Right now it only hosts the Chipotle reviews. Future planned articles are the free stuff and maybe bathroom rankings.

There are also other articles (VIP, Clubs, etc.) that are already tagged as "Social".

Some possible alternatives:
- Misc.
- Other
- Fun
- Recreation

Please comment any suggestions or comments you have.

**Comment by aminoa** [comment]
Recreation; not perfect but fits better.

**Comment by rilieo** [comment]
hi, could i take this issue please. i think recreation is the best out of the synonyms for social lol
