### ISSUE TITLE
Add global search

### ISSUE THREAD

**Issue by nedjulius** [BUGS-NYU/nyu-cs-wiki#47]
Noticed that we're missing a global search bar. Would be great to have one.

https://docusaurus.io/docs/search

**Comment by nedjulius** [comment]
Requested algolia service for our CS wiki. It is free for all open-source projects: https://docsearch.algolia.com/

**Comment by calvinatian** [comment]
Some documentation on integrating algolia: https://docusaurus.io/docs/search

**Comment by nedjulius** [comment]
Algolia approved search service for us! Will add a PR integrating algolia

**Comment by nedjulius** [comment]
For some reason the crawler doesn't work, checking
