### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by nedjulius** [BUGS-NYU/nyu-cs-wiki#48]
Need to purchase SSL cert @calvinatian

<img width="436" alt="image" src="https://github.com/BUGS-NYU/nyu-cs-wiki/assets/45975811/71632df1-9038-43d3-a424-030f879a34d6">

**Comment by calvinatian** [comment]
If you manually use `https` it should work. Enforcing https will be fixed soon.
![image](https://github.com/BUGS-NYU/nyu-cs-wiki/assets/48587962/da0afa8e-c16a-4ee8-b2cd-c35137a5b48a)

**Comment by calvinatian** [comment]
Should be fixed
