### ISSUE TITLE
Content License

### ISSUE THREAD

**Issue by sachiniyer** [BUGS-NYU/nyu-cs-wiki#79]
Is the content also licensed by MIT?

As I understand it, licensing the content under MIT, means anyone can take the content without attribution. You can address this one thing specifically with the MIT with attribution license.

However, Creative Commons licensing has a ton more stuff about creative works specifically (e.g. DRM).

I would propose keeping code licensed under MIT, while licensing the content under CC (something like BY-SA or BY-NA-SA). This has been done in many other projects (e.g. [privacy guides](https://github.com/privacyguides/privacyguides.org) [license chooser](https://github.com/github/choosealicense.com/)...)

**Comment by aminoa** [comment]
Thanks for pointing this out -  I think CC BY-SA is a good fit for the project. Also, I'd like to relicense this project to use GPLv3 (the standard license chosen for BUGS projects).

**Comment by sachiniyer** [comment]
# Effects of different licenses with examples
## Effects of BY
| Action                     | Decision      |
| --------------------------| --------------- |
| Attribution             | :white_check_mark: |
| Stays CC                  | :x:  |
| Other Colleges      | :white_check_mark: |
|Other OS projects | :white_check_mark: |
| Proprietary Projects | :white_check_mark:    |
| Proprietary LLMS    | :white_check_mark:   |
| Open Source LLMS    | :white_check_mark:     |

## Effects of BY-NC
| Action                     | Decision      |
| --------------------------| --------------- |
| Attribution             | :white_check_mark: |
| Stays CC                  | :x:  |
| Other Colleges      | :white_check_mark: |
|Other OS projects | :white_check_mark: |
| Proprietary Projects | :x:                 |
| Proprietary LLMS    | :x:                 |
| Open Source LLMS    | :white_check_mark: |

## Effects of BY-SA
| Action                     | Decision      |
| --------------------------| --------------- |
| Attribution             | :white_check_mark: |
| Stays CC                  | :white_check_mark:  |
| Other Colleges      | :white_check_mark: |
|Other OS projects | :white_check_mark: |
| Proprietary Projects | :white_check_mark:    |
| Proprietary LLMS    | :white_check_mark:   |
| Open Source LLMS    | :white_check_mark:     |

## Effects of BY-SA-NC
| Action                     | Decision      |
| --------------------------| --------------- |
| Attribution             | :white_check_mark: |
| Stays CC                  | :white_check_mark: |
| Other Colleges      | :white_check_mark:  |
|Other OS projects | :white_check_mark: |
| Proprietary Projects | :x:                 |
| Proprietary LLMS    | :x:                 |
| Open Source LLMS    | :white_check_mark: |

**Comment by aminoa** [comment]
Ah thanks, appreciate the reference. I made a forum post in the BUGS Discord to open up discussion to more community members.

**Comment by sachiniyer** [comment]
Closing, as I now see a license in the repo.
